### ISSUE TITLE
Async\Semaphore holds unto finished Awaitables unecessarily

### ISSUE THREAD

**Issue by mmckeen** [hhvm/hsl#105]
In objects of Semaphore with many calls to `waitForAsync` we develop a long Awaitable tree with many items in the tree representing finished Awaitables.

Since these Awaitables are still part of a tree, they can't be cleaned up by `gc_collect_cycles` or the circular reference GC.

With a patch like 
```
-    $this->activeGen = async {
-      concurrent {
-        await $this->activeGen;
-        await $gen;
-      }
-    };
+
+    if (\HH\Asio\has_finished($this->activeGen)) {
+      $this->activeGen = $gen;
+    } else {
+      $this->activeGen = async {
+        concurrent {
+          await $this->activeGen;
+          await $gen;
+        }
+      };
+    }
```
we should be able to free references to the finished Awaitable tree and let the GC/gc_collect_cycles clean it up.

**Comment by fredemmott** [comment]
I'm reaching out to the internal experts on this.

**Comment by fredemmott** [comment]
@jano has an alternative fix for this that should land shortly :)

**Comment by ryangreenberg** [comment]
I have a long-running process that uses HHAST to parse ~4500 files. I upgraded a couple weeks ago from hhvm 4.1 to hhvm 4.13, with the corresponding HHAST release, and the process started getting routine OOM fatal errors. I just found a workaround, which is to run `HHAST\from_file_async` on batches of files in a separate process (roughly `cat files | xargs -n $batch_size HHAST\from_file_async`).

I suspect this issue with Async\Semaphore is the reason I was getting OOMs. When a valid .hhast.parser-cache file exists, HHAST reads and uses that synchronously (no memory issues issues in long-running process); when no valid cache is available, the internal ParserQueue that checks for calls hh_parse async using Async\Semaphore.

If there's any validation of that fix I can do that would be helpful, LMK.

**Comment by jano** [comment]
@mmckeen, thanks for the report. Please reopen if the diff does not fix the issue.

**Comment by lexidor** [comment]
Is my implementation of `AsyncQueue` has able to benefit from this patch?
```HACK
class AsyncQueue {
  private ?Awaitable<mixed> $queue;

  public async function doAfterPreviousAsync<T>((function(): Awaitable<T>) $item): Awaitable<T> {
    $prev = $this->queue;
    $next = async {
      try {
        await $prev;
      } catch (\Exception $_) {
        // We don't care about exceptions from our previous, they belong to the caller before us.
      }
      return await $item();
    };
    $this->queue = $next;
    return await $next;
  }
}
```

**Comment by jano** [comment]
@lexidor, nope, because AsyncQueue can't start the $item before $prev is done... but setting $prev to null before awaiting the $item() would help

**Comment by lexidor** [comment]
Okay, thanks for the free performance boost. :stuck_out_tongue_winking_eye:

**Comment by mmckeen** [comment]
I'm going to run this fix through our internal repro to make sure it fixes our issue, will update this if it doesn't.

**Comment by mmckeen** [comment]
The new patch resolves the leak we observed, does this deserve a test case to prevent from being introduced again?
