### ISSUE TITLE
[ Backport ] Put `HH\Lib\Ref<T>` in every hsl version

### ISSUE THREAD

**Issue by lexidor** [hhvm/hsl#108]
Hi,

I was looking to include the class `HH\Lib\Ref<T>` in every minor version of the HSL starting from the one that quizlet is currently using.
That way I can reliably use it in versions of HHVM that are nolonger receiving support.

`Tyron Jung` offered me to help on how to make something like this happen.

**Comment by fredemmott** [comment]
As it appears that this class is available for all supported versions of HHVM (starting with HSL v4.7 for HHVM 4.8), we won't be able to spend much time here
- where there are existing branches, please send a pull request against that branch
- if not, please provide a list of wanted versions, and I'll push branches

Pull requests will also need to change composer.json/travis.yml as appropriate

**Comment by tyronjung-quizlet** [comment]
We're currently on HSL `1.4.0`.

**Comment by fredemmott** [comment]
@tyronjung-quizlet any chance you can get to >= v3.26.0 ?

That's also unsupported, but critically, includes https://github.com/hhvm/hsl/commit/172fb92cf8e77b9edf357cd2f769b9279023cb7d

**Comment by fredemmott** [comment]
It's a relatively small change:

```
e046cdb (tag: v3.26.0) Update required HHVM version
3f1f9ec HH_FIXME ill-typed comparisons
8789f34 add missing use namespace (fix travis)
6f788dd Promote {Keyset, Vec}\fb\filter_with_key
f14db9e Allow HSL test failures against stable OSS HHVM release
c199a7c Add C\reduce_with_key
d955774 Updating CONTRIBUTING.md and README
c505718 Stop testing the HSL against HHVM 3.24
ea9f2a0 Second pass on marking HSL as reactive
faaf9e5 Revert D7678095: [RxHack] First pass on marking HSL as reactive
bd6c2e6 First pass on marking HSL as reactive
f023333 Add license metadata
172fb92 Relicense the Hack Standard Library
d7b87f9 Reassign core/hack/lib tests to hack
```

+ some commits and corresponding revert commits

**Comment by tyronjung-quizlet** [comment]
> any chance you can get to >= v3.26.0 ?

On prod we're running HHVM v3.25.3, so I don't think we can at the moment...

**Comment by fredemmott** [comment]
Hmm, given the history I'm comfortable cherry-picking the relicensing commits to the branch; this does mean that this process will involve changing from BSD+PATENTS-licensed HSL to MIT-licensed HSL.

**Comment by fredemmott** [comment]
I've just:
- pushed relicensing commits to the v4.1.x branch
- created the v3.26.x branch

It looks like there's already branches for all other releases you need; let me know if I've missed anything

**Comment by fredemmott** [comment]
Actually, sorry, I should revert that. I don't think it's reasonable for a .z update to change the license

**Comment by lexidor** [comment]
I've spoken with @tyronjung-quizlet and they can define `Ref<T>` for themselves. Hammock will just require the MIT hsl version, so it works out of the box for everyone on HHVM 3.26 and above. People one 3.25 will need to polyfill.

**Comment by tyronjung-quizlet** [comment]
Sorry for the trouble @fredemmott. @lexidor that sounds good.

**Comment by lexidor** [comment]
Sorry for making such a mess while migrating the tests.
They currently target hhvm 3.y.z instead of 3.y-latest.
We should use the `-latest` tag if we are being proper, but there will never be a new hhvm 3.y.z, so it is not strictly needed.

**Comment by lexidor** [comment]
Every version now has `Ref<T>` closing.
