### ISSUE TITLE
Switch to using default expressions

### ISSUE THREAD

**Issue by simonwelsh** [hhvm/hsl#14]
A quick look over the source showed that this pattern is fairly common:
```hack
function any<T>(
  Traversable<T> $traversable,
  ?(function(T): bool) $predicate = null,
): bool {
  $predicate = $predicate ?? fun('boolval');
```

This can be changed to:
```hack
function any<T>(
  Traversable<T> $traversable,
  (function(T): bool) $predicate = fun('boolval'),
): bool {
```

which removes the nullable and exposes the default behaviour as part of the function signature rather than relying on documentation.

**Comment by kmeht** [comment]
We originally used default expressions, but internally, we need these functions to be compatible with `fb_intercept`. Unfortunately, `fb_intercept` doesn't play well with `fun()` as a default inside namespaces, so we did this as a workaround.

**Comment by kmeht** [comment]
Closing this out for now, as it's intentional. Thanks for reporting!
