### ISSUE TITLE
Locale-aware Str\ functions have differing behavior on Linux and MacOS

### ISSUE THREAD

**Issue by fredemmott** [hhvm/hsl#165]
MacOS uses UTF-8 for locales that don't specify an encoding, e.g. `en_US` - unlike on Linux, which assumes a single-byte encoding. This gives hack programs varying cross-platform behavior.

**Comment by Atry** [comment]
Try en_US.UTF8 ?

**Comment by fredemmott** [comment]
This isn't a matter of choose the wrong locale, it's that the HSL has incorrect behavior for some locales.

`.UTF8` is invalid (but accepted by some linux systems); `.UTF-8` is character based everywhere.

`en_US` without `.UTF-8` is byte-based on Linux, character-based in MacOS - for some functions only. It is defined as consistently byte-based for the HSL (in the design and docs, and it's basically essential for correctness with some HHVM optimizations), but it isn't.

**Comment by fredemmott** [comment]
So, this is intentional, and I forgot about it. Importantly, we are explicitly recognizing `en_US` as a multibyte locale in macos, and handling it consistently - this isn't that some functions behave differently to others:

https://github.com/facebook/hhvm/blob/7e621926354146812f1d9532614947270e1e7ff2/hphp/runtime/base/locale.cpp#L130-L139

MacOS terminal behavior:

```
fredemmott@fredemmott-fbmbp /tmp % echo 😀😀😀😀 | LC_ALL=en_US sed 's/^.//'
😀😀😀
fredemmott@fredemmott-fbmbp /tmp % echo 😀😀😀😀 | LC_ALL=C sed 's/^.//'
���😀😀😀
fredemmott@fredemmott-fbmbp /tmp % echo 😀😀😀😀 | LC_ALL=en_US.US-ASCII sed 's/^.//'
���😀😀😀
```

Given that the behavior of str\ is internally consistent, I'm leaning towards considering this 'not a bug', but adjusting the tests to use explicit single-byte encodings, like fr_FR.ISO8859-15 and tr_TR.ISO8859-9

it should then test that on linux, it's treated like 'C', but on MacOS, it is not. We could potentially lint against creating a locale without specifying a charset - which might not be a bad idea anyway, to hint people towards UTF-8 regardless.

**Comment by fredemmott** [comment]
- the format of locale strings is explicitly implementation-defined in POSIX
- I'm a little worried about weird interactions with OS\ if we interpret the active thread locale differently to C code
