### ISSUE TITLE
hsl link at top of documentation page is a 404

### ISSUE THREAD

**Issue by BobertForever** [hhvm/hsl#27]
When clicking on the hsl link at the top of the documentation pages, it tries to navigate to https://hhvm.github.io/hsl/, which is a 404.

**Comment by fredemmott** [comment]
I had a look at this a while back; as far as I can tell, it's generated by the gh-pages infra, and we don't have direct control over it.

This'll be fixed when the HSL is stablisized: I'll be moving the docs to be part of docs.hhvm.com

**Comment by fredemmott** [comment]
I'm not going to be spending more time on this, but leaving open for now as I"ll happily take a PR :)
