### ISSUE TITLE
Link to real-world example bin/generate-docs.php is broken in README

### ISSUE THREAD

**Issue by rubycalling** [hhvm/hsl#65]
The file bin/generate-docs.php mentioned in the [README](https://github.com/hhvm/hsl/blob/master/README.md) has been deleted since commit ef61c015ab5969d10c2b0d66cfbc1dd20b13ec17 (5 Jan 2018) - Should we remove the reference?

**Comment by fredemmott** [comment]
Yep, will do; that's basically the https://github.com/hhvm/hh-apidoc project now, though for HSL, it's being built as part of docs.hhvm.com
