### ISSUE TITLE
Hsl version of php's substr function

### ISSUE THREAD

**Issue by akiljames83** [hhvm/hsl#87]
HSL has implementations for many of the core php string functions but it does not include a commonly used function `substr`. Implementing this should not be difficult and promotes use of hsl over php's standard library

**Comment by kmeht** [comment]
Have you considered `Str\slice`?

**Comment by azjezz** [comment]
`HH\Lib\Str\slice($str, $offset, ?$length);` would be `HSL`s equivalent to `PHP`s `\substr` 

see : https://github.com/hhvm/hsl/blob/master/src/str/select.php#L15-L40
